version: '3'
services:
    php:
        image: php:fpm
        volumes:
            - ./app:/app
    composer:
        image: composer:latest
        command: ["composer", "install"]
        volumes:
            - ./app:/app